# Generated by Django 5.0.1 on 2024-01-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='auth_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
