# Generated by Django 5.0.1 on 2024-01-31 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_author_city_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='city_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.city'),
        ),
    ]
